image: Visual Studio 2015
configuration:
- Debug
- DebugDLL
- DebugDLL_fixed
- Release
- ReleaseDLL
- ReleaseDLL_fixed

platform:
- Win32
- x64

build:
  project: win32\VS2015\opus.sln
  parallel: true
  verbosity: minimal

test_script:
- cmd: >-
    %APPVEYOR_BUILD_FOLDER%\win32\VS2015\%PLATFORM%\%CONFIGURATION%\test_opus_api.exe

    %APPVEYOR_BUILD_FOLDER%\win32\VS2015\%PLATFORM%\%CONFIGURATION%\test_opus_decode.exe

    %APPVEYOR_BUILD_FOLDER%\win32\VS2015\%PLATFORM%\%CONFIGURATION%\test_opus_encode.exe
